compile:
	javac *.java

run:
	java -classpath ./mysql-connector-java-3.0.10-stable-bin.jar:. TestDB

clean:
	rm -f *.class

solve:
	java -classpath ./mysql-connector-java-3.0.10-stable-bin.jar:. TestClass

test: compile run clean
